[workspace]
members = ["crates/rustcraft", "crates/rustcraft_protocol", "crates/rustcraft_server", "crates/rustcraft_client", "crates/rustcraft_macros", "crates/rustcraft_dedicated_server"]
resolver = "3"
